-- AlterTable
ALTER TABLE "Chatroom" ADD COLUMN     "isCrafteeRead" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isCrafterRead" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lastChatTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
